sudo: false  # Now the build will be running on the new container based platform

language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - "pypy"
  - "pypy3"

addons:
  apt:
    sources:
      - build-essential

install:
 - pip install --install-option="--no-cython-compile" Cython 
 - pip install .

script:
 - cd `mktemp -d`  # Navigate into a temporary directory to avoid loading the local code
 - nosetests --verbosity=2 nxmetis.tests.test_metis

notifications:
  email: false
